<?php

namespace Database\Seeders;

use App\Models\HierarchyOutlet;
use Illuminate\Database\Seeder;

class HierarchyOutletSeeder extends Seeder
{
    /**
     * Run database seeds for hierarchy_outlets with verified 41 regional records.
     */
    public function run(): void
    {
        if (\App\Models\HierarchyOutlet::count() > 0) {
            return;
        }
        $data = [
            // 1. BALI BARAT (Denpasar Branch - Herbianto) - Soft Greenish Tint
            [
                'kabupaten' => 'JEMBRANA',
                'cluster' => 'BALI BARAT',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.139',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'TABANAN',
                'cluster' => 'BALI BARAT',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.139',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'BULELENG',
                'cluster' => 'BALI BARAT',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.139',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 2. BALI TENGAH (Denpasar Branch - Herbianto) - Soft Warm Neutral Tint
            [
                'kabupaten' => 'BADUNG',
                'cluster' => 'BALI TENGAH',
                'mitra' => 'PT. CATALIST INTEGRA PRIMA SUKSES',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.690',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KOTA DENPASAR',
                'cluster' => 'BALI TENGAH',
                'mitra' => 'PT. CATALIST INTEGRA PRIMA SUKSES',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.690',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 3. BALI TIMUR (Denpasar Branch - Herbianto) - Soft Peach/Orange Tint
            [
                'kabupaten' => 'GIANYAR',
                'cluster' => 'BALI TIMUR',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.322',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KLUNGKUNG',
                'cluster' => 'BALI TIMUR',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.322',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'BANGLI',
                'cluster' => 'BALI TIMUR',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.322',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KARANG ASEM',
                'cluster' => 'BALI TIMUR',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'DENPASAR',
                'jumlah_outlet' => '1.322',
                'manager_branch' => 'Herbianto',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 4. ENDE SIKKA (Flores Branch - Waskitho Anjar Prabowo) - Soft Green Tint
            [
                'kabupaten' => 'SIKKA',
                'cluster' => 'ENDE SIKKA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '954',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'ENDE',
                'cluster' => 'ENDE SIKKA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '954',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 5. FLORES TIMUR (Flores Branch - Waskitho Anjar Prabowo) - Soft Pink/Lavender Tint
            [
                'kabupaten' => 'ALOR',
                'cluster' => 'FLORES TIMUR',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '1.053',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'LEMBATA',
                'cluster' => 'FLORES TIMUR',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '1.053',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'FLORES TIMUR',
                'cluster' => 'FLORES TIMUR',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '1.053',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 6. MANGGARAI (Flores Branch - Waskitho Anjar Prabowo) - Sky Blue Tint
            [
                'kabupaten' => 'NGADA',
                'cluster' => 'MANGGARAI',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '2.024',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'MANGGARAI',
                'cluster' => 'MANGGARAI',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '2.024',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'MANGGARAI BARAT',
                'cluster' => 'MANGGARAI',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '2.024',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'NAGEKEO',
                'cluster' => 'MANGGARAI',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '2.024',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'MANGGARAI TIMUR',
                'cluster' => 'MANGGARAI',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'FLORES',
                'jumlah_outlet' => '2.024',
                'manager_branch' => 'Waskitho Anjar Prabowo',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 7. KUPANG ROTE (Kupang Branch - Adhy Yanwar) - Soft Cream/Warm Tint
            [
                'kabupaten' => 'KUPANG',
                'cluster' => 'KUPANG ROTE',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.050',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'ROTE NDAO',
                'cluster' => 'KUPANG ROTE',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.050',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KOTA KUPANG',
                'cluster' => 'KUPANG ROTE',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.050',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 8. MALAKA TIMTIM B (Kupang Branch - Adhy Yanwar) - Sky Blue Tint
            [
                'kabupaten' => 'TIMOR TENGAH SELATAN',
                'cluster' => 'MALAKA TIMTIM B',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.476',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'TIMOR TENGAH UTARA',
                'cluster' => 'MALAKA TIMTIM B',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.476',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'BELU',
                'cluster' => 'MALAKA TIMTIM B',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.476',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'MALAKA',
                'cluster' => 'MALAKA TIMTIM B',
                'mitra' => 'PT. NARINDO SOLUSI TELEKOMUNIKASI',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.476',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 9. SUMBA (Kupang Branch - Adhy Yanwar) - Warm Orange/Peach Tint
            [
                'kabupaten' => 'SUMBA BARAT',
                'cluster' => 'SUMBA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.319',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'SUMBA TIMUR',
                'cluster' => 'SUMBA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.319',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'SUMBA TENGAH',
                'cluster' => 'SUMBA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.319',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'SUMBA BARAT DAYA',
                'cluster' => 'SUMBA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.319',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'SABU RAIJUA',
                'cluster' => 'SUMBA',
                'mitra' => 'CV. RAJAWALI CELLULAR',
                'branch' => 'KUPANG',
                'jumlah_outlet' => '1.319',
                'manager_branch' => 'Adhy Yanwar',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 10. LOMBOK (Mataram Branch - Kurnia Budi Setiawan) - Neutral Soft Gray Tint
            [
                'kabupaten' => 'LOMBOK BARAT',
                'cluster' => 'LOMBOK',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '2.524',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'LOMBOK TENGAH',
                'cluster' => 'LOMBOK',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '2.524',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'LOMBOK TIMUR',
                'cluster' => 'LOMBOK',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '2.524',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'LOMBOK UTARA',
                'cluster' => 'LOMBOK',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '2.524',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KOTA MATARAM',
                'cluster' => 'LOMBOK',
                'mitra' => 'PT AKAR DAYA',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '2.524',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 11. SUMBAWA BARAT (Mataram Branch - Kurnia Budi Setiawan) - Light Cyan Tint
            [
                'kabupaten' => 'SUMBAWA',
                'cluster' => 'SUMBAWA BARAT',
                'mitra' => 'PT BERKAH KARUNIA KREASI',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '986',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'SUMBAWA BARAT',
                'cluster' => 'SUMBAWA BARAT',
                'mitra' => 'PT BERKAH KARUNIA KREASI',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '986',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],

            // 12. SUMBAWA TIMUR (Mataram Branch - Kurnia Budi Setiawan) - Soft Warm Tint
            [
                'kabupaten' => 'DOMPU',
                'cluster' => 'SUMBAWA TIMUR',
                'mitra' => 'PT KINARYA SELARAS SOLUSI',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '1.262',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'BIMA',
                'cluster' => 'SUMBAWA TIMUR',
                'mitra' => 'PT KINARYA SELARAS SOLUSI',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '1.262',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
            [
                'kabupaten' => 'KOTA BIMA',
                'cluster' => 'SUMBAWA TIMUR',
                'mitra' => 'PT KINARYA SELARAS SOLUSI',
                'branch' => 'MATARAM',
                'jumlah_outlet' => '1.262',
                'manager_branch' => 'Kurnia Budi Setiawan',
                'group_class' => 'bg-white hover:bg-gray-50/80',
                'badge_color' => 'bg-gray-100 text-gray-800',
            ],
        ];

        HierarchyOutlet::query()->delete();

        foreach ($data as $item) {
            HierarchyOutlet::create($item);
        }
    }
}
